Repository kubernetes/contributor-site, pull requests merged in 2018-11, with the labels that each got.

#34 Bob is doing a bunch of work here, he should be an OWNER
  OWNERS
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#37 Add makefile and docker build support
  Dockerfile
  Makefile
  README.md
  gen-site.sh
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 remove unneeded content
  gen-site.sh
  kcommunity_exclude.list
Labels: approved, cncf-cla: yes, lgtm, size/M
