Repository kubernetes/contributor-site, pull requests merged in 2018-08, with the labels that each got.

#10 fix header string check
  gen-site.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12 Add Google Analytics
  layouts/partials/original/head.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#16 Remove design proposals
  exclude.list
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 Update content structure
  config.toml
  exclude.list
  gen-site.sh
  include.list
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 Remove event notes but allow rest of events directory
  exclude.list
Labels: approved, cncf-cla: yes, lgtm, size/XS

#19 Tweak style to align with kubernetes.io
  config.toml
  static/css/overrides.css
  static/images/texture.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#20 Change to CNCF GA code
  layouts/partials/original/head.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#22 add build check to pull latest content
  gen-site.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
