Repository kubernetes/contributor-site, pull requests merged in 2018-10, with the labels that each got.

#28 add insecure image link regex
  gen-site.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#32 Move calendar up one directory and add pointers for ical subscriptions
  layouts/partials/head.html
  managed_content/calendar.md
  managed_content/events/calendar.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#33 Add Calendar to the sidebar
  config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Netlify Build Error fix
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#36 Update README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L
