Repository kubernetes/contributor-site, pull requests merged in 2019-04, with the labels that each got.

#42 Add event calendar
  Makefile
  assets/css/fullcalendar/core.min.css
  assets/css/fullcalendar/daygrid.min.css
  assets/js/calendar.js
  assets/js/fullcalendar/core.min.js
  assets/js/fullcalendar/daygrid.min.js
  assets/js/fullcalendar/google-calendar.min.js
  assets/js/fullcalendar/moment.min.js
  assets/sass/calendar.sass
  assets/sass/style.sass
  layouts/partials/css.html
  layouts/partials/javascript.html
  layouts/shortcodes/calendar.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#43 Switch to list view for calendar
  assets/css/fullcalendar/daygrid.min.css
  assets/css/fullcalendar/list.min.css
  assets/js/calendar.js
  assets/js/fullcalendar/daygrid.min.js
  assets/js/fullcalendar/list.min.js
  assets/js/fullcalendar/moment.min.js
  config.toml
  layouts/partials/css.html
  layouts/partials/javascript.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 Update calendar api key.
  assets/js/calendar.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#46 Revamp README instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#47 Add code of conduct link to site sidebar
  config.toml
  layouts/partials/sidebar.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#48 Fix README header link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 Add AnchorJS support
  assets/js/app.js
  assets/sass/main.sass
  content/other-page.md
  layouts/partials/article.html
  layouts/partials/javascript.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#53 Using go.k8s.io for pointing to OWNERS docs
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 Add smooth scrolling for mobile
  assets/sass/style.sass
Labels: approved, cncf-cla: yes, lgtm, size/XS

#54 Add basic footer
  assets/sass/footer.sass
  assets/sass/main.sass
  assets/sass/navbar.sass
  assets/sass/style.sass
  layouts/_default/baseof.html
  layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#55 Add custom youtube shortcode
  README.md
  assets/sass/style.sass
  layouts/shortcodes/youtube.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 Initial cut of contributor's guide
  config.toml
  content/Events/community-meeting.md
  content/Events/contributor-summit/2019-barcelona.md
  content/Events/meet-our-contributors.md
  content/Events/office-hours.md
  content/_index.md
  content/calendar.md
  content/contributors-guide/_index.md
  content/contributors-guide/second.md
  content/contributors-guide/third.md
  content/guide/OWNERS
  content/guide/_index.md
  content/guide/bug-bounty.md
  content/guide/cheatsheet.md
  content/guide/coding-conventions.md
  content/guide/community-expectations.md
  content/guide/github-workflow.md
  content/guide/help-wanted.md
  content/guide/issue-triage.md
  content/guide/non-code-contributions.md
  content/guide/owners.md
  content/guide/pull-requests.md
  content/guide/style-guide.md
  content/other-page.md
  content/other/_index.md
  content/other/sub-page.md
  static/img/git_workflow.png
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#63 Fix YouTube shortcode
  assets/sass/style.sass
  layouts/shortcodes/youtube.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#64 Add schedule shortcode
  content/Events/contributor-summit/2019-barcelona.md
  layouts/shortcodes/schedule.html
Labels: approved, cncf-cla: yes, lgtm, size/S
