Repository kubernetes/contributor-site, pull requests merged in 2020-12, with the labels that each got.

#181 Restore website minification via hugo minify
  Makefile
  layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#182 celebration: switch to sched embed for schedule
  content/en/events/kcc2020/schedule.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#183 Update faq and events for celebration
  content/en/events/kcc2020/activities.md
  content/en/events/kcc2020/faq.md
  content/en/events/kcc2020/name.png
  content/en/events/kcc2020/nickname.png
  content/en/events/kcc2020/server.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#184 Add pronoun examples
  content/en/events/kcc2020/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#185 📝 Add a guide on internet board games for the CC docs.
  content/en/events/kcc2020/activities.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#186 Add how-to-join section to contributor celebration
  content/en/events/kcc2020/activities.md
  content/en/events/kcc2020/add-server.png
  content/en/events/kcc2020/channels.png
  content/en/events/kcc2020/coc-emoji.png
  content/en/events/kcc2020/coc.png
  content/en/events/kcc2020/dm-from-bot.png
  content/en/events/kcc2020/faq.md
  content/en/events/kcc2020/help-channel.png
  content/en/events/kcc2020/how-to-join.md
  content/en/events/kcc2020/instructions-to-connect.png
  content/en/events/kcc2020/join-server.png
  content/en/events/kcc2020/schedule.md
  content/en/events/kcc2020/settings-cog.png
  content/en/events/kcc2020/user-volume.png
  content/en/events/kcc2020/verification.png
  content/en/events/kcc2020/voice-video-settings.png
  content/en/events/kcc2020/voice-video.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 Add photobooth info for eoy event
  content/en/events/kcc2020/activities.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#188 Update celebration faq
  content/en/events/kcc2020/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#190 update celebration help channel name
  content/en/events/kcc2020/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#193 Pull in the release logo too.
  external-sources/kubernetes/sig-release
Labels: approved, cncf-cla: yes, lgtm, size/XS

#192 fix few minor typos
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 Add sig-list to resources
  content/en/resources/community-groups/.gitignore
  external-sources/kubernetes/community
Labels: approved, cncf-cla: yes, lgtm, size/XS

#196 Archive celebration
  content/en/events/past-events/2020/_index.md
  content/en/events/past-events/2020/kcc2020/_index.md
  content/en/events/past-events/2020/kcc2020/activities.md
  content/en/events/past-events/2020/kcc2020/add-server.png
  content/en/events/past-events/2020/kcc2020/channels.png
  content/en/events/past-events/2020/kcc2020/coc-emoji.png
  content/en/events/past-events/2020/kcc2020/coc.png
  content/en/events/past-events/2020/kcc2020/dm-from-bot.png
  content/en/events/past-events/2020/kcc2020/faq.md
  content/en/events/past-events/2020/kcc2020/help-channel.png
  content/en/events/past-events/2020/kcc2020/how-to-join.md
  content/en/events/past-events/2020/kcc2020/instructions-to-connect.png
  content/en/events/past-events/2020/kcc2020/invited.png
  content/en/events/past-events/2020/kcc2020/join-server.png
  content/en/events/past-events/2020/kcc2020/name.png
  content/en/events/past-events/2020/kcc2020/nickname.png
  content/en/events/past-events/2020/kcc2020/schedule.md
  content/en/events/past-events/2020/kcc2020/server.png
  content/en/events/past-events/2020/kcc2020/settings-cog.png
  content/en/events/past-events/2020/kcc2020/user-volume.png
  content/en/events/past-events/2020/kcc2020/verification.png
  content/en/events/past-events/2020/kcc2020/voice-video-settings.png
  content/en/events/past-events/2020/kcc2020/voice-video.png
  content/en/events/past-events/2020/kcc2020/yagpdb.png
  content/en/events/past-events/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M
