Repository kubernetes/contributor-site, pull requests merged in 2020-11, with the labels that each got.

#173 Kubernetes Contributor Celebration Site
  content/en/events/kcc2020/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#174 Update Celebration Page
  content/en/events/kcc2020/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#176 Add celebration faq and activities
  content/en/events/kcc2020/_index.md
  content/en/events/kcc2020/activities.md
  content/en/events/kcc2020/faq.md
  content/en/events/kcc2020/yagpdb.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 Add coc section to celebration event
  content/en/events/kcc2020/_index.md
  content/en/events/kcc2020/activities.md
  content/en/events/kcc2020/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#179 fix skribbl.io link
  content/en/events/kcc2020/activities.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 Add celebration event image and initial schedule
  content/en/events/kcc2020/_index.md
  content/en/events/kcc2020/invited.png
  content/en/events/kcc2020/schedule.md
Labels: approved, cncf-cla: yes, lgtm, size/M
