Repository kubernetes/contributor-site, pull requests merged in 2020-09, with the labels that each got.

#164 feat: add netlify rebuild periodic job
  .github/workflows/netlify-periodic-build.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 Bump release page to 1.20
  external-sources/kubernetes/sig-release
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Blog Post: Contributing to the Development Guide
  content/en/blog/2020/contributing-to-the-development-guide/index.md
  content/en/blog/2020/contributing-to-the-development-guide/jorge-castro-code-of-conduct.jpg
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash
