Repository kubernetes/contributor-site, pull requests merged in 2020-10, with the labels that each got.

#166 Update README: https://k8s.dev/ is now live
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#168 Allow specifying alternative tool for containerized local testing
  Makefile
  README.md
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#171 Add Google Custom Search
  config.toml
  content/en/search.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 disable offline search
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS
