Repository kubernetes/contributor-site, pull requests merged in 2020-01, with the labels that each got.

#88 enh: Adding icon for external links
  layouts/partials/sidebar.html
  static/img/external.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#90 fix: Reverting the API Key exposed
  assets/js/calendar.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#87 fix: Adding Slack and k-dev channel link
  content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#91 fix: External icon was not setted with rel path
  layouts/partials/sidebar.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 Support for non-kubernetes org external sources
  config.toml
  content/.gitignore
  external-sources/cncf/foundation
  external-sources/kubernetes/community
  hack/gen-content.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#95 feat: Upgrading to goldmark markdown renderer
  Makefile
  config.toml
  content/Events/meet-our-contributors.md
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#97 fix: Merging the .gitignore with one present in root
  .gitignore
  content/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#99 Making calendar work for different view
  assets/css/fullcalendar/daygrid.min.css
  assets/js/calendar.js
  assets/js/fullcalendar/daygrid.min.js
  assets/js/fullcalendar/moment.min.js
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#101 Fixing calendar links and beautifying it
  assets/js/calendar.js
  assets/sass/calendar.sass
  layouts/shortcodes/calendar.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#102 Fix parsing of HUGO_VERSION from netlify.toml in the Makefile.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Add release schedule link.
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 Update link to KEP-0005
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#106 Import release timeline doc
  .gitignore
  Makefile
  config.toml
  external-sources/kubernetes/sig-release
  hack/gen-content.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
