Repository kubernetes/contributor-site, pull requests merged in 2020-02, with the labels that each got.

#108 Rendering all sidebar contents and layout enhancements
  assets/sass/main.sass
  layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#110 Fix reference link expansion
  hack/gen-content.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#111 Missing links in nav-bar and calendar updates
  assets/sass/calendar.sass
  layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 Adding calendar into Community Calendar section from index
  content/Events/community-calendar.md
  content/Events/meet-our-contributors.md
  content/Events/office-hours.md
  layouts/shortcodes/calendar.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 Fix bug with readme to named file generation
  config.toml
  hack/gen-content.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#115 Addition of Events on Index Events Page
  content/Events/_index.md
  content/Events/contributor-summits.md
  layouts/shortcodes/events.html
  static/img/summit_image.JPG
  static/img/summit_na.jpg
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#117 Adding external sources in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#118 Clicking on logo should redirect to home
  layouts/partials/sidebar.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Revamping Site Evolution section
  README.md
  content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S
