Repository kubernetes/contributor-site, pull requests merged in 2021-09, with the labels that each got.

#234 Fix cheatsheet link in CONTRIBUTING
  CONTRIBUTING.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#242 feat(kcsna2021): update site with new contrib summit info
  content/en/events/kcsna2021/_index.md
  content/en/events/kcsna2021/cfp.md
  content/en/events/kcsna2021/faq.md
  content/en/events/kcsna2021/registration.md
  content/en/events/kcsna2021/schedule.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#243 Update summit page with social info
  content/en/events/kcsna2021/LACC.jpg
  content/en/events/kcsna2021/_index.md
  content/en/events/kcsna2021/cfp.md
  content/en/events/kcsna2021/faq.md
  content/en/events/kcsna2021/location.md
  content/en/events/kcsna2021/lucky-strike.jpg
  content/en/events/kcsna2021/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/M
