Repository kubernetes/contributor-site, pull requests merged in 2021-07, with the labels that each got.

#205 Chris' story: non-code contribution
  content/en/blog/2021/non-code-contribution.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/M, tide/merge-method-squash

#225 Stub 2021 summit page
  content/en/events/kcsna2021/banner.jpeg
  content/en/events/kcsna2021/index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#227 Fix broken link
  content/en/blog/2021/non-code-contribution.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#228 Update summit landing page
  content/en/events/kcsna2021/index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#230 Update links to use git.k8s.io where possible
  README.md
  SECURITY_CONTACTS
  content/en/blog/2020/contributing-to-the-development-guide/index.md
  content/en/blog/2021/contributor-story.md
  content/en/blog/2021/non-code-contribution.md
  content/en/community/code-of-conduct.md
  content/en/welcome/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#231 Add KCSNA2021 summit information
  content/en/events/kcsna2021/_index.md
  content/en/events/kcsna2021/banner.jpeg
  content/en/events/kcsna2021/banner.png
  content/en/events/kcsna2021/faq.md
  content/en/events/kcsna2021/hotel.jpeg
  content/en/events/kcsna2021/location.md
  content/en/events/kcsna2021/registration.md
  content/en/events/kcsna2021/schedule.md
Labels: approved, cncf-cla: yes, lgtm, size/L
