Repository kubernetes/contributor-site, pull requests merged in 2021-12, with the labels that each got.

#264 kcc2021: Add activities
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#266 Add para for Krafternetes. Full schedule will come later.
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#267 kcc2021: add missing krafternetes ToC entry
  content/en/events/kcc2021/activities.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#265 Blog post for Contributor Celebration 2021
  content/en/blog/2021/contributor-celebration.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#268 Add ttrpg nights to activities page for KCC 21
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes, tide/merge-method-squash

#269 Updated the FAQ with info on voice channels for KCC 21
  content/en/events/kcc2021/faq.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#271 Add webclient instructions for the captcha.
  content/en/events/kcc2021/how-to-join.md
Labels: lgtm, approved, cncf-cla: yes, size/XS, tide/merge-method-squash

#270 Remove BakeOff from the description, as it's cancelled.
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#272 Add Cloud Native Cookbook and Kitchen Activity
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes, tide/merge-method-squash

#273 fix rpg sign up link
  content/en/events/kcc2021/activities.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#274 update dpg
  content/en/events/kcc2021/activities.md
Labels: lgtm, size/S, approved, cncf-cla: yes, tide/merge-method-squash

#275 update index with winners
  content/en/community/.gitignore
  content/en/community/awards/2021/index.md
  content/en/community/awards/_index.md
  content/en/events/kcc2021/_index.md
Labels: lgtm, size/L, approved, cncf-cla: yes, tide/merge-method-squash

#276 awards/2021: update github username
  content/en/community/awards/2021/index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#277 Archive celebration
  content/en/blog/2021/contributor-celebration.md
  content/en/community/awards/2021/index.md
  content/en/events/past-events/2021/kcc2021/_index.md
  content/en/events/past-events/2021/kcc2021/activities.md
  content/en/events/past-events/2021/kcc2021/add-server.png
  content/en/events/past-events/2021/kcc2021/channels.png
  content/en/events/past-events/2021/kcc2021/coc-emoji.png
  content/en/events/past-events/2021/kcc2021/coc.png
  content/en/events/past-events/2021/kcc2021/dm-from-bot.png
  content/en/events/past-events/2021/kcc2021/faq.md
  content/en/events/past-events/2021/kcc2021/help-channel.png
  content/en/events/past-events/2021/kcc2021/how-to-join.md
  content/en/events/past-events/2021/kcc2021/instructions-to-connect.png
  content/en/events/past-events/2021/kcc2021/invited.png
  content/en/events/past-events/2021/kcc2021/join-server.png
  content/en/events/past-events/2021/kcc2021/name.png
  content/en/events/past-events/2021/kcc2021/nickname.png
  content/en/events/past-events/2021/kcc2021/schedule.md
  content/en/events/past-events/2021/kcc2021/server.png
  content/en/events/past-events/2021/kcc2021/settings-cog.png
  content/en/events/past-events/2021/kcc2021/user-volume.png
  content/en/events/past-events/2021/kcc2021/verification.png
  content/en/events/past-events/2021/kcc2021/voice-video-settings.png
  content/en/events/past-events/2021/kcc2021/voice-video.png
  content/en/events/past-events/2021/kcc2021/yagpdb.png
Labels: lgtm, approved, cncf-cla: yes, size/M
