Repository kubernetes/contributor-site, pull requests merged in 2021-11, with the labels that each got.

#254 changed kubernetes/org link
  content/en/resources/services.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#258 Bootstrap 2021 Contributor Celebration website
  content/en/events/kcc2021/_index.md
  content/en/events/kcc2021/activities.md
  content/en/events/kcc2021/add-server.png
  content/en/events/kcc2021/channels.png
  content/en/events/kcc2021/coc-emoji.png
  content/en/events/kcc2021/coc.png
  content/en/events/kcc2021/dm-from-bot.png
  content/en/events/kcc2021/faq.md
  content/en/events/kcc2021/help-channel.png
  content/en/events/kcc2021/how-to-join.md
  content/en/events/kcc2021/instructions-to-connect.png
  content/en/events/kcc2021/invited.png
  content/en/events/kcc2021/join-server.png
  content/en/events/kcc2021/name.png
  content/en/events/kcc2021/nickname.png
  content/en/events/kcc2021/schedule.md
  content/en/events/kcc2021/server.png
  content/en/events/kcc2021/settings-cog.png
  content/en/events/kcc2021/user-volume.png
  content/en/events/kcc2021/verification.png
  content/en/events/kcc2021/voice-video-settings.png
  content/en/events/kcc2021/voice-video.png
  content/en/events/kcc2021/yagpdb.png
  content/en/events/past-events/2020/kcc2020/_index.md
  content/en/events/past-events/2021/_index.md
  content/en/events/past-events/2021/kcsna/LACC.jpg
  content/en/events/past-events/2021/kcsna/_index.md
  content/en/events/past-events/2021/kcsna/banner.png
  content/en/events/past-events/2021/kcsna/faq.md
  content/en/events/past-events/2021/kcsna/hotel.jpeg
  content/en/events/past-events/2021/kcsna/location.md
  content/en/events/past-events/2021/kcsna/lucky-strike.jpg
  content/en/events/past-events/2021/kcsna/registration.md
  content/en/events/past-events/2021/kcsna/schedule.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#257 Fix K8sContributors twitter handle link in K8s.dev website
  content/en/resources/services.md
Labels: lgtm, approved, cncf-cla: yes, size/XS, tide/merge-method-squash

#260 Update OWNERS
  OWNERS
Labels: lgtm, approved, cncf-cla: yes, size/XS

#262 Add 2021 Celebration registration information
  content/en/events/kcc2021/_index.md
  content/en/events/kcc2021/faq.md
  content/en/events/kcc2021/how-to-join.md
  content/en/events/kcc2021/schedule.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#261 Update KCSNA2021 Event
  content/en/events/past-events/2021/kcsna/_index.md
  content/en/events/past-events/2021/kcsna/faq.md
  content/en/events/past-events/2021/kcsna/location.md
  content/en/events/past-events/2021/kcsna/registration.md
  content/en/events/past-events/2021/kcsna/schedule.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#255 Using mermaid for diagrams blog
  content/en/blog/2021/improve-with-mermaid-diagrams/ingress-figure.svg
  content/en/blog/2021/improve-with-mermaid-diagrams/mermaid-blog-outline.svg
  content/en/blog/2021/improve-with-mermaid-diagrams/mermaid-diagrams.md
  content/en/blog/2021/improve-with-mermaid-diagrams/mermaid-sequence-diagram.svg
  content/en/blog/2021/improve-with-mermaid-diagrams/pod-topo-constraint-02.svg
Labels: lgtm, size/L, approved, cncf-cla: yes
