Repository kubernetes/contributor-site, pull requests merged in 2022-05, with the labels that each got.

#306 Added page for the Social
  content/en/events/kcseu/_index.md
  content/en/events/kcseu/casadelmar.jpg
  content/en/events/kcseu/faq.md
  content/en/events/kcseu/location.md
  content/en/events/kcseu/schedule.md
  content/en/events/kcseu/social.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#307 Add more links, SIG meeting and Docs information to schedule page.
  content/en/events/kcseu/_index.md
  content/en/events/kcseu/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#308 Update schedule.md Uncon Sess 3 format
  content/en/events/kcseu/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#309 Update information on bringing guests to the social.
  content/en/events/kcseu/faq.md
  content/en/events/kcseu/social.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#310 Update to k8s.dev/release to 1.25
  external-sources/kubernetes/sig-release
Labels: lgtm, approved, cncf-cla: yes, size/XS

#311 Replace schedule with sched
  content/en/events/kcseu/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#304 Kubernetes 1.24: contextual logging blog post
  content/en/blog/2022/2022-05-25-contextual-logging.md
Labels: lgtm, size/L, approved, cncf-cla: yes
