Repository kubernetes/contributor-site, pull requests merged in 2022-02, with the labels that each got.

#283 SIG Multicluster spotlight blog
  content/en/blog/2022/sig-multicluster-spotlight-blog.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#286 Fix alculquicondor name in contributors awards
  content/en/community/awards/2021/index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#287 Fix community-groups link on services page
  content/en/resources/services.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#288 SIG Node CI Subproject Celebrates Two Years of Test Improvements
  content/en/blog/2022/2022-02-16-sig-node-ci-subproject-celebrates/index.md
  content/en/blog/2022/2022-02-16-sig-node-ci-subproject-celebrates/release-mostly-green.png
  content/en/blog/2022/2022-02-16-sig-node-ci-subproject-celebrates/serial-tests-green.png
Labels: lgtm, sig/node, size/L, approved, cncf-cla: yes
