Repository kubernetes/contributor-site, pull requests merged in 2022-04, with the labels that each got.

#297 Add EU 2022 summit details
  content/en/events/kcseu/_index.md
  content/en/events/kcseu/faq.md
  content/en/events/kcseu/location.md
  content/en/events/kcseu/registration.md
  content/en/events/kcseu/schedule.md
  content/en/events/past-events/2021/kcsna/_index.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#298 Added information about session setup.
  content/en/events/kcseu/_index.md
  content/en/events/kcseu/faq.md
  content/en/events/kcseu/location.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#293 blog:bot helper CI Job
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/K8s Triage bot Helper CI Job_ ‘make update’.md
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/artifacts.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/checklists.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/codespaces.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/codespaces2.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/completed_checklist.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/failing_test_cases.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/jenkins.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/k8s_ci_failed_tests.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/tpku_command.png
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/vscode.png
Labels: lgtm, size/L, approved, cncf-cla: yes

#301 Updates on schedule, masking, other information about the Summit
  content/en/events/kcseu/_index.md
  content/en/events/kcseu/faq.md
  content/en/events/kcseu/location.md
  content/en/events/kcseu/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#302 Revise CI bot helper article
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/k8s-ci-bot-make-update-helper.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#303 CI Job Blog
  content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/K8s-ci-bot-make-update-helper.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
