Repository kubernetes/contributor-site, pull requests merged in 2022-08, with the labels that each got.

#323 Add SIG Docs Spotlight blog article
  content/en/blog/2022/sig_docs_spotlight_blog.md
Labels: lgtm, size/L, approved, cncf-cla: yes, tide/merge-method-squash

#327 Add kcsna2022 site
  content/en/events/2022/kcseu/_index.md
  content/en/events/2022/kcsna/_index.md
  content/en/events/2022/kcsna/faq.md
  content/en/events/2022/kcsna/location.md
  content/en/events/2022/kcsna/registration.md
  content/en/events/2022/kcsna/schedule.md
  content/en/events/2022/kcsna/social.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#326 Add sftim to approvers
  OWNERS
Labels: lgtm, approved, cncf-cla: yes, size/XS

#318 Blogpost: Add post about enhancements on kubernetes release team
  content/en/blog/2022/enhancing-kubernetes-one-kep-at-a-time.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#314 blog: meet our contributors APAC China region
  content/en/blog/2022/meet-our-contributors-APAC-China-region-03.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#328 Add kcsna 2022 registration
  content/en/events/2022/kcsna/registration.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#319 Add SIG Storage Spotlight blog article
  content/en/blog/2022/sig-storage-spotlight.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#315 changed the marketing-team subdirectory name to contributor-comms
  content/en/blog/2021/non-code-contribution.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#333 Adding late-breaking change about testing option
  content/en/events/2022/kcsna/registration.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
