Repository kubernetes/contributor-site, pull requests merged in 2022-09, with the labels that each got.

#330 Implementing Official CVE Feed alpha
  content/en/blog/2022/2022-09-12-Implementing-the-Auto-Refreshing-Official-CVE-Feed/index.md
Labels: lgtm, sig/docs, size/L, approved, cncf-cla: yes, sig/security

#335 Add 2019 award winners.
  content/en/community/awards/2019/index.md
Labels: lgtm, sig/contributor-experience, approved, cncf-cla: yes, size/M

#336 Add CFP for kcsna 2022
  content/en/events/2022/kcsna/cfp.md
  content/en/events/2022/kcsna/schedule.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#334 Blog: New Release Opt-in process
  content/en/blog/2022/enhancements-process-update.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#337 update k8s.dev/release to the latest cycle
  external-sources/kubernetes/sig-release
Labels: lgtm, approved, cncf-cla: yes, size/XS

#341 Fix link to CFP page
  content/en/events/2022/kcsna/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
