Repository kubernetes/contributor-site, pull requests merged in 2023-05, with the labels that each got.

#403 Bump release page to 1.28
  external-sources/kubernetes/sig-release
Labels: lgtm, approved, cncf-cla: yes, size/XS

#399 README cleanup
  README.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#404 Add SIG Network Spotlight
  content/en/blog/2023/sig-network-spotlight.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#405 Added recordings link to Kubecon summit 2023
  content/en/events/2023/kcseu/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
