Repository kubernetes/contributor-site, pull requests merged in 2023-08, with the labels that each got.

#418 Add SIG Contribex Spotlight blog article
  content/en/blog/2023/sig-contribex-spotlight.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#412 Update for KCSNA23
  content/en/events/2023/kcseu/_index.md
  content/en/events/2023/kcsna/_index.md
  content/en/events/2023/kcsna/faq.md
  content/en/events/2023/kcsna/location.md
  content/en/events/2023/kcsna/registration.md
  content/en/events/2023/kcsna/schedule.md
  content/en/events/2023/kcsna/social.md
  static/_redirects
Labels: lgtm, size/L, approved, cncf-cla: yes

#419 Fix missing/wrong content for KCSNA launch.
  content/en/events/2023/kcsna/location.md
  content/en/events/2023/kcsna/schedule.md
  content/en/events/2023/kcsna/social.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#420 Fix CfP links
  content/en/events/2023/kcsna/_index.md
  content/en/events/2023/kcsna/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#417 add pages for China KCS 2023: kubernetes contributor summit
  content/en/events/2023/kcscn/_index.md
  content/en/events/2023/kcscn/faq.md
  content/en/events/2023/kcscn/location.md
  content/en/events/2023/kcscn/registration.md
  content/en/events/2023/kcscn/schedule.md
  static/_redirects
Labels: lgtm, size/L, approved, cncf-cla: yes, tide/merge-method-squash

#421 Import and use the CNCF Code of Conduct
  Makefile
  content/en/community/code-of-conduct.md
  content/en/includes/.gitignore
  content/en/includes/_index.md
  external-sources/cncf/foundation
  external-sources/kubernetes/community
  layouts/shortcodes/include.html
Labels: lgtm, size/L, approved, cncf-cla: yes

#374 Bump Hugo version to 0.112
  Dockerfile
  Makefile
  layouts/partials/head.html
  layouts/partials/sidebar-tree.html
  netlify.toml
Labels: lgtm, size/L, approved, cncf-cla: yes

#423 KCS China 2023:Update mail address, CFP and registration link
  content/en/events/2023/kcscn/_index.md
  content/en/events/2023/kcscn/faq.md
  content/en/events/2023/kcscn/registration.md
  content/en/events/2023/kcscn/schedule.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#426 Repetition phrase fixed
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
