Repository kubernetes/contributor-site, pull requests merged in 2023-02, with the labels that each got.

#370 Sig Instrumentation Spotlight
  content/en/blog/2023/sig-instrumentation-spotlight.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#363 Update list of goals for the site
  README.md
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#371 Updated dead link on welcome page
  content/en/welcome/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#372 Fix up 2023 SIG Instrumentation spotlight blog article
  content/en/blog/2023/sig-instrumentation-spotlight.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#347 Create new contributor onboarding e-learning series WIP
  content/en/docs/onboarding/01-starting-out.md
  content/en/docs/onboarding/02-getting-into-github.md
  content/en/docs/onboarding/03-pull-requests.md
  content/en/docs/onboarding/04-issues-management.md
  content/en/docs/onboarding/05-development.md
  content/en/docs/onboarding/06-testing.md
  content/en/docs/onboarding/07-code-review.md
  content/en/docs/onboarding/08-community.md
  content/en/docs/onboarding/09-documentation.md
  content/en/docs/onboarding/10-architecture.md
  content/en/docs/onboarding/_index.md
  layouts/partials/revealjs.html
  layouts/reveal/baseof.html
  layouts/reveal/single.html
Labels: lgtm, approved, cncf-cla: yes, size/XXL

#373 KCSEU2023 Registration goes live
  content/en/events/2023/kcseu/registration.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#377 Blog post introducing kwok
  content/en/blog/2023/2023-03-01-introducing-kwok/index.md
  content/en/blog/2023/2023-03-01-introducing-kwok/kwok.svg
  content/en/blog/2023/2023-03-01-introducing-kwok/manage-clusters.svg
Labels: lgtm, approved, cncf-cla: yes, size/M
