Repository kubernetes/contributor-site, pull requests merged in 2023-04, with the labels that each got.

#392 blog: updated E2E best practices
  content/en/blog/2023/e2e-testing-best-practices.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#391 Update links on the welcome page
  content/en/welcome/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#393 Update summit schedule URL
  content/en/events/2023/kcseu/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#395 Centralizing aliases under _redirects
  content/en/community/awards/2019/index.md
  content/en/community/awards/2020/index.md
  content/en/community/awards/2021/index.md
  content/en/community/awards/2022/index.md
  content/en/community/awards/_index.md
  content/en/community/code-of-conduct.md
  content/en/docs/comms/_index.md
  content/en/docs/onboarding/_index.md
  content/en/events/2020/kcc/_index.md
  content/en/events/2021/kcc/_index.md
  content/en/events/2021/kcsna/_index.md
  content/en/events/2022/kcseu/_index.md
  content/en/events/2022/kcsna/_index.md
  content/en/events/2023/kcseu/_index.md
  content/en/resources/community-calendar.md
  content/en/resources/services.md
  static/_redirects
Labels: lgtm, approved, cncf-cla: yes, size/M

#376 Drop Google Universal Analytics (UA) ID
  config.toml
Labels: lgtm, approved, cncf-cla: yes, size/XS

#397 add a little detail to summit social location
  content/en/events/2023/kcseu/location.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#400 Added photos for contributors summit
  content/en/events/2023/kcseu/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
