Repository kubernetes/contributor-site, pull requests merged in 2024-09, with the labels that each got.

#524 Link to upcoming Kubernetes v1.32
  external-sources/kubernetes/sig-release
Labels: lgtm, approved, cncf-cla: yes, size/XS

#520 Add SIG Scheduling spotlight
  content/en/blog/2024/sig-scheduling-spotlight.md
Labels: lgtm, size/L, approved, cncf-cla: yes, tide/merge-method-squash

#530 Spotlight for CNCF DHHWG
  content/en/blog/2024/cncf-dhhwg/cncf-dhhwg-chicago.jpg
  content/en/blog/2024/cncf-dhhwg/cncf-dhhwg-paris.jpg
  content/en/blog/2024/cncf-dhhwg/cncf-dhhwg-spotlight.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash
