Repository kubernetes/contributor-site, pull requests merged in 2024-03, with the labels that each got.

#480 KCSEU24: Adding Map to Social
  content/en/events/2024/kcseu/KCS-walking-directions-to-Pavilion-6_La-Serre-small.webp
  content/en/events/2024/kcseu/KCS-walking-directions-to-Pavilion-6_La-Serre.webp
  content/en/events/2024/kcseu/social.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#481 KCSEU24: Fixing relative links in social map
  content/en/events/2024/kcseu/social.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#483 Add recordings and photos to KCSNA 2023
  content/en/events/2023/kcsna/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#484 Add "Go workspaces for k/k" blog post
  content/en/blog/2024/go-workspaces.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#485 Fix link to social from location page
  content/en/events/2024/kcseu/location.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#486 Don't default Hugo version in Dockerfile
  Dockerfile
Labels: lgtm, approved, cncf-cla: yes, size/XS

#487 Bump to latest Hugo
  netlify.toml
Labels: lgtm, approved, cncf-cla: yes, size/XS

#490 Improve fetch for KEP data
  Makefile
  layouts/shortcodes/keps-data.html
Labels: lgtm, size/S, approved, cncf-cla: yes

#491 Added photos link to KCSEU 2024
  content/en/events/2024/kcseu/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#492 Make `hack/gen-content.sh` discover GNU `grep` and `sed` on macOS
  hack/gen-content.sh
Labels: lgtm, approved, cncf-cla: yes, size/M
