Repository kubernetes/contributor-site, pull requests merged in 2024-12, with the labels that each got.

#551 Add Award winners for 2024
  content/en/community/awards/2024/index.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#553 fix sig-node kubernetes contributor award 2024
  content/en/community/awards/2024/index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#554 fix format problems of kcs awards and some comments
  content/en/community/awards/2021/index.md
  content/en/community/awards/2023/index.md
  content/en/community/awards/2024/index.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#555 fix: update the primary colour to align with the k8s branding
  assets/scss/_variables.scss
Labels: lgtm, approved, cncf-cla: yes, size/XS

#556 feat: move from a toml hugo config to a yaml one
  hugo.yaml
Labels: lgtm, size/L, approved, cncf-cla: yes
