Repository kubernetes/contributor-site, pull requests merged in 2024-06, with the labels that each got.

#507 add scaffold page for KCNA2024
  content/en/events/2024/kcsna/_index.md
  content/en/events/2024/kcsna/faq.md
  content/en/events/2024/kcsna/location.md
  content/en/events/2024/kcsna/registration.md
  content/en/events/2024/kcsna/schedule.md
  content/en/events/2024/kcsna/social.md
  static/_redirects
Labels: lgtm, size/L, approved, cncf-cla: yes

#498 Add SIG Node spotlight interview
  content/en/blog/2024/sig-node-spotlight/Lake_Geneva_and_the_Alps.jpg
  content/en/blog/2024/sig-node-spotlight/sig-node-spotlight.md
Labels: lgtm, sig/contributor-experience, size/L, approved, cncf-cla: yes

#511 Add statement on streaming.
  content/en/events/2024/kcsna/faq.md
  content/en/events/2024/kcsna/location.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#510 hack/gen-content.sh: fix bogus reference link mangling
  hack/gen-content.sh
Labels: lgtm, approved, cncf-cla: yes, size/XS

#513 Add CFP info for KCSNA
  content/en/events/2024/kcsna/_index.md
Labels: lgtm, approved, cncf-cla: yes, size/XS

#514 Update CFP on the schedule page.
  content/en/events/2024/kcsna/schedule.md
Labels: lgtm, approved, cncf-cla: yes, size/XS
