Repository kubernetes/contributor-site, pull requests merged in 2025-03, with the labels that each got.

#574 update OWNERS to add sig-contribex-leads
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, cncf-cla: yes, size/XS

#573 Add SIG Apps spotlight
  content/en/blog/2025/sig-apps-spotlight.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#575 SIG Apps spotlight Nit fixes
  content/en/blog/2025/sig-apps-spotlight.md
Labels: lgtm, size/S, approved, cncf-cla: yes

#577 Add SayakMukhopadhyay as reviewer :tada:
  OWNERS
Labels: lgtm, size/S, approved, cncf-cla: yes

#561 refactor: remove pygments and other properties that are already default
  hugo.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M
