Repository kubernetes/contributor-site, pull requests merged in 2025-01, with the labels that each got.

#559 fix: copying inside the container perms issue
  Makefile
Labels: lgtm, approved, cncf-cla: yes, size/XS

#563 feat: upgraded docsy to 0.6.0
  package-lock.json
  package.json
Labels: lgtm, approved, cncf-cla: yes, size/XXL

#526 Add SIG Architecture: Enhancements spotlight
  content/en/blog/2024/sig-arch-enhancements-spotlight.md
Labels: lgtm, size/L, approved, cncf-cla: yes

#566 cri-api policies
  OWNERS_ALIASES
  content/en/docs/code/OWNERS
  content/en/docs/code/_index.md
  content/en/docs/code/cri-api-dev-policies.md
  content/en/docs/code/cri-api-version-skew-policy.md
Labels: lgtm, sig/node, size/L, approved, cncf-cla: yes

#569 Upgrade docsy to 0.7.2
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  content/en/_index.md
  layouts/_default/content.html
  layouts/calendar/baseof.html
  layouts/calendar/list.html
  layouts/community/baseof.html
  layouts/community/list.html
  layouts/docs/list.html
  layouts/partials/navbar.html
  layouts/resources/baseof.html
  layouts/resources/list.html
  layouts/swagger/list.html
  package-lock.json
  package.json
Labels: lgtm, approved, cncf-cla: yes, size/XXL
